[package]
name = "spinning-square"
version = "0.1.0"
authors = ["Drew Powers <drew@pow.rs>"]
edition = "2018"

[[bin]]
name = "spinning-square"

[dependencies]
hsl = "0.1.1"
piston = "0.49.0"
piston2d-graphics = "0.36.0"
pistoncore-glutin_window = "0.63.0"
piston2d-opengl_graphics = "0.72.0"
